version: '3.7'
services:
  db:
    build: ./couchbase
    container_name: todo-couchbase
    volumes:
      - ~/couchbase/node1:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    networks:
      - my_network
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=default
      - COUCHBASE_BUCKET_PASSWORD=
  todo_app:
    build: .
    container_name: todo-backend
    environment:
      COUCHBASE_HOST: db
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network:
    driver: bridge